### PR TITLE
Fixed namespace variable not visible and added public apis with Schema.SObject param.

### PR DESCRIPTION
**Pull request by triandicAnt**
1. Fixed `namespace` variable visibility.
2. Added public instance/static methods to support  `Schema.SObjectField` param along with `String`.
3. Added a method to return `Database.QueryLocator`.
4. Added public visibility for `objectType`.

### CODE REVIEW

**Comment by HenryRLee** [comment]
Thank you for your pull request.

I like the first part of your commits, i.e. adding the `Schema.SObjectField` as a parameter type. It was something I'd like to do in short.

As for the other parts, there are a few small fixes I'd to request:

To add public visibility to the `objectType`, I'd recommend using a public method `getObjectType` or `getSObjectType`.

Secondly, I'd recommend changing the name of the `toQueryLocator` method to `getQueryLocator`, to follow the name conversion in the `Database` class.

Finally, I'd be much appreciated if you could split these parts into different commits.

**Comment by triandicAnt** [comment]
Sure.. I will start working on that.

**Comment by HenryRLee** [comment]
Sorry I was trying to make some changes to your branch, but accidentally close this PR.

**Comment by HenryRLee** [comment]
#21 and #22 are the related PR, where the commits are under your name, which will still make you a contributor to this repository. Thank you.

**Pull request closed without merging**
